spring.application.name: stream-global-table-sample
spring.cloud.stream.bindings.process-in-0:
  destination: mysql.mydb.transactions
spring.cloud.stream.bindings.process-in-1:
  destination: mysql.mydb.user_profile
spring.cloud.stream.bindings.process-out-0:
  destination: intermediate-topic
spring.cloud.stream.kafka.streams.bindings.process-in-1:
  consumer:
    materializedAs: all-users
spring.cloud.stream.kafka.streams.binder:
  configuration:
    default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    commit.interval.ms: 1000